# Generated by Django 5.2.5 on 2025-08-21 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussion.sujet'),
        ),
    ]
